spring:
  datasource:
    url: jdbc:mysql://localhost:3306/feed
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
    open-in-view: false #OSIV 를 true로 설정하면, request가 반환될 때 까지 커넥션을 보유
#  data:
#    redis:
#      host: localhost
#      port: 6379

logging.level:
  org.hibernate.SQL: debug # 이거 끄면 format_sql 적용 안됨
#  org.hibernate.type: trace


secret-key: secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey