-- 사용자 데이터 삽입
INSERT INTO COMMUNITY_USER (REG_DT, UPD_DT, FOLLOWER_COUNT, FOLLOWING_COUNT, IMAGE_URL, NAME)
VALUES (now(), now(), 0, 0, '','User 1');
INSERT INTO COMMUNITY_USER (REG_DT, UPD_DT, FOLLOWER_COUNT, FOLLOWING_COUNT, IMAGE_URL, NAME)
VALUES (now(), now(), 0, 0, '','User 2');
INSERT INTO COMMUNITY_USER (REG_DT, UPD_DT, FOLLOWER_COUNT, FOLLOWING_COUNT, IMAGE_URL, NAME)
VALUES (now(), now(), 0, 0, '','User 3');
INSERT INTO COMMUNITY_USER (REG_DT, UPD_DT, FOLLOWER_COUNT, FOLLOWING_COUNT, IMAGE_URL, NAME)
VALUES (now(), now(), 0, 0, '','User 4');
INSERT INTO COMMUNITY_USER (REG_DT, UPD_DT, FOLLOWER_COUNT, FOLLOWING_COUNT, IMAGE_URL, NAME)
VALUES (now(), now(), 0, 0, '','User 5');

INSERT INTO COMMUNITY_USER_RELATION (REG_DT, UPD_DT, FOLLOWING_USER_ID, FOLLOWER_USER_ID)
VALUES (now(), now(), 1, 2);

INSERT INTO COMMUNITY_USER_RELATION (REG_DT, UPD_DT, FOLLOWING_USER_ID, FOLLOWER_USER_ID)
VALUES (now(), now(), 1, 3);

INSERT INTO COMMUNITY_USER_RELATION (REG_DT, UPD_DT, FOLLOWING_USER_ID, FOLLOWER_USER_ID)
VALUES (now(), now(), 3, 4);

INSERT INTO COMMUNITY_USER_RELATION (REG_DT, UPD_DT, FOLLOWING_USER_ID, FOLLOWER_USER_ID)
VALUES (now(), now(), 3, 5);

INSERT INTO COMMUNITY_POST (COMMENT_COUNT, LIKE_COUNT, AUTHOR_ID, REG_DT, UPD_DT, CONTENT, STATE)
VALUES (0, 0, 2, now(), now(), '2번 작성', 'PUBLIC');

INSERT INTO COMMUNITY_POST (COMMENT_COUNT, LIKE_COUNT, AUTHOR_ID, REG_DT, UPD_DT, CONTENT, STATE)
VALUES (0, 0, 3, now(), now(), '3번 작성', 'PUBLIC');

INSERT INTO COMMUNITY_POST (COMMENT_COUNT, LIKE_COUNT, AUTHOR_ID, REG_DT, UPD_DT, CONTENT, STATE)
VALUES (0, 0, 4, now(), now(), '4번 작성', 'PUBLIC');

INSERT INTO COMMUNITY_POST (COMMENT_COUNT, LIKE_COUNT, AUTHOR_ID, REG_DT, UPD_DT, CONTENT, STATE)
VALUES (0, 0, 5, now(), now(), '5번 작성', 'PUBLIC');



