deploy-job:
  runs-on: ubuntu-latest
  needs: build-job
  steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: twitter-application
        path: build/libs/

    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/twitter-${{ needs.build-job.outputs.release }}.jar ${{ secrets.EC2_USER_NAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER_NAME }}/twitter-${{ needs.build-job.outputs.release }}.jar

        # 환경 변수 설정 후 스프링 부트 애플리케이션 실행
        ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER_NAME }}@${{ secrets.EC2_HOST }} "
          export SPRING_PROFILES_ACTIVE=prod && 
          pgrep java | xargs kill -9; 
          nohup java -jar /home/${{ secrets.EC2_USER_NAME }}/twitter-${{ needs.build-job.outputs.release }}.jar > app.log 2>&1 &
        "
        rm -f private_key.pem
